### PR TITLE
fix deletion of unallocated pointer.

### PR DESCRIPTION
**Pull request by roymacdonald**
This was giving me some problems, although, shouldn't it be better if this was an unique_ptr instead of a raw pointer?

### CODE REVIEW

**Comment by npisanti** [comment]
i will integrate this but then i have to check it again, the last time i made a static analysis run there were some things to fix about that, the pointer is allocated with `malloc` by c code so i should substitute `delete` with `free()`.

Yes maybe i should also switch to better pointers, i'm not that much "modern c++" at the moment, but i'll put it in my TODO list.

**Comment by roymacdonald** [comment]
Hi, I see.
I started the implementation of an unique_ptr but I realized that an std::vector suits this better.
I'll make a PR if I get it to work.
best!

**Comment by npisanti** [comment]
perfect, thank you for working on this =)

**Comment by roymacdonald** [comment]
No problem! Its me the one that should be thanking you.
cheers

**Pull request merged**
